name: Deploy Yakubov-S Registrations to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            export NVM_DIR="/root/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            if ! command -v pm2 &> /dev/null
            then
              npm install -g pm2
            fi

            cd /home/${{ secrets.SERVER_USER }}

            if [ ! -d "yakubov-s-medicalog-uz" ]; then
              git clone https://github.com/farruhzoirov/yakubov-s-medicalog-uz.git
            fi

            cd yakubov-s-medicalog-uz
            git reset --hard HEAD
            git pull origin main

            npm install --force
            npm run build

            cat > .env <<EOL
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            LOGIN=${{ secrets.LOGIN }}
            PASSWORD=${{ secrets.PASSWORD }}
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            ADMIN_1_ID=${{ secrets.ADMIN_1_ID }}
            ADMIN_2_ID=${{ secrets.ADMIN_2_ID }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
            GOOGLE_SHEET_ID=${{ secrets.GOOGLE_SHEET_ID }}
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
            EOL

            pm2 start dist/main.js --name yakubov-s-medicalog-uz || pm2 restart yakubov-s-medicalog-uz
            pm2 save